- hosts: mysql app monitoring nginx gitlab runner 
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    marker
  roles:
   - Install_Node_Exporter