before_script:
  - apt update
  - apt install ssh rsync -y
  - eval $(ssh-agent -s)
  - echo "$ssh_key" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

stages:         
  - deploy

deploy-job:      
  stage: deploy
  script:
    - echo "Deploying application..." 
    - ssh -o StrictHostKeyChecking=no marker@app.kharitonov.su sudo chown marker /var/www/wordpress/ -R
    - rsync -vz -e "ssh -o StrictHostKeyChecking=no" ./* marker@app.kharitonov.su:/var/www/wordpress/
    - ssh -o StrictHostKeyChecking=no marker@app.kharitonov.su rm -rf /var/www/wordpress/.git
    - ssh -o StrictHostKeyChecking=no marker@app.kharitonov.su sudo chown www-data /var/www/wordpress/ -R